name: pytorch_platform_interface
description: A common platform interface for the pytorch plugin.
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.1"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  path: ^1.8.2
  path_provider: ^2.0.11
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
