name: sv_algoritms
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  ffmpeg_kit_flutter: ^5.1.0
  flutter:
    sdk: flutter
  matrix2d: ^1.0.3
  numdart: ^1.0.0
  opencv_4: ^1.0.0
  scidart: ^0.0.2-dev.12

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
