name: pytorch_android
description: Android implementation of the pytorch plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.1"

flutter:
  plugin:
    implements: pytorch
    platforms:
      android:
        package: com.sportsvisio.pytorch
        pluginClass: PytorchPlugin
        dartPluginClass: PytorchAndroid

dependencies:
  flutter:
    sdk: flutter
  pytorch_platform_interface:
    path: ../pytorch_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.2
