name: pytorch_macos

on:
  pull_request:
    paths:
      - ".github/workflows/pytorch_macos.yaml"
      - "pytorch_macos/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/pytorch_macos.yaml"
      - "pytorch_macos/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.1
      working_directory: pytorch_macos
